package com.example.backend1.community;

import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
public class CommunitySchemaInitializer implements ApplicationRunner {

    private final JdbcTemplate jdbcTemplate;

    public CommunitySchemaInitializer(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void run(ApplicationArguments args) {
        jdbcTemplate.execute("""
                alter table community_posts
                add column if not exists like_count integer not null default 0
                """);

        jdbcTemplate.execute("""
                create table if not exists community_post_likes (
                    id bigint generated by default as identity primary key,
                    post_id bigint not null,
                    user_id bigint not null,
                    created_at timestamp(6) with time zone not null default now(),
                    constraint fk_community_post_likes_post
                        foreign key (post_id) references community_posts(id),
                    constraint fk_community_post_likes_user
                        foreign key (user_id) references users(id),
                    constraint uk_community_post_likes_post_user
                        unique (post_id, user_id)
                )
                """);

        jdbcTemplate.execute("""
                create index if not exists idx_community_post_likes_post_id
                on community_post_likes(post_id)
                """);
        jdbcTemplate.execute("""
                create index if not exists idx_community_post_likes_user_id
                on community_post_likes(user_id)
                """);

        jdbcTemplate.execute("""
                create table if not exists community_reports (
                    id bigint generated by default as identity primary key,
                    target_type varchar(20) not null,
                    target_id bigint not null,
                    reporter_id bigint not null,
                    reason varchar(40) not null,
                    detail varchar(500),
                    created_at timestamp(6) with time zone not null default now(),
                    constraint fk_community_reports_reporter
                        foreign key (reporter_id) references users(id),
                    constraint uk_community_reports_target_user
                        unique (target_type, target_id, reporter_id)
                )
                """);

        jdbcTemplate.execute("""
                create index if not exists idx_community_reports_target
                on community_reports(target_type, target_id)
                """);
        jdbcTemplate.execute("""
                create index if not exists idx_community_reports_reporter_id
                on community_reports(reporter_id)
                """);
        jdbcTemplate.execute("""
                create index if not exists idx_community_reports_created_at
                on community_reports(created_at)
                """);
    }
}
