// 전국 시/도 + 시/군 단위 지역 목록 (구 단위는 나누지 않음).
// 특별시/광역시/특별자치시는 하위 시/군이 없고 그 자체가 최하 지역 단위다.

export type RegionCity = {
  code: string;
  name: string;
};

export type RegionSiDo = {
  code: string;
  name: string;
  /** 하위 시/군 목록. 특별시/광역시/특별자치시는 없음(그 자체가 최하 단위). */
  cities?: RegionCity[];
};

export const REGION_SI_DO_LIST: RegionSiDo[] = [
  { code: "SEOUL", name: "서울특별시" },
  { code: "BUSAN", name: "부산광역시" },
  { code: "DAEGU", name: "대구광역시" },
  { code: "INCHEON", name: "인천광역시" },
  { code: "GWANGJU", name: "광주광역시" },
  { code: "DAEJEON", name: "대전광역시" },
  { code: "ULSAN", name: "울산광역시" },
  { code: "SEJONG", name: "세종특별자치시" },
  {
    code: "GYEONGGI",
    name: "경기도",
    cities: [
      { code: "SUWON", name: "수원시" },
      { code: "SEONGNAM", name: "성남시" },
      { code: "GOYANG", name: "고양시" },
      { code: "YONGIN", name: "용인시" },
      { code: "BUCHEON", name: "부천시" },
      { code: "ANSAN", name: "안산시" },
      { code: "ANYANG", name: "안양시" },
      { code: "NAMYANGJU", name: "남양주시" },
      { code: "HWASEONG", name: "화성시" },
      { code: "PYEONGTAEK", name: "평택시" },
      { code: "UIJEONGBU", name: "의정부시" },
      { code: "SIHEUNG", name: "시흥시" },
      { code: "PAJU", name: "파주시" },
      { code: "GIMPO", name: "김포시" },
      { code: "GWANGMYEONG", name: "광명시" },
      { code: "GWANGJU_GG", name: "광주시" },
      { code: "GUNPO", name: "군포시" },
      { code: "ICHEON", name: "이천시" },
      { code: "YANGJU", name: "양주시" },
      { code: "OSAN", name: "오산시" },
      { code: "GURI", name: "구리시" },
      { code: "ANSEONG", name: "안성시" },
      { code: "POCHEON", name: "포천시" },
      { code: "UIWANG", name: "의왕시" },
      { code: "HANAM", name: "하남시" },
      { code: "YEOJU", name: "여주시" },
      { code: "YANGPYEONG", name: "양평군" },
      { code: "DONGDUCHEON", name: "동두천시" },
      { code: "GWACHEON", name: "과천시" },
      { code: "GAPYEONG", name: "가평군" },
      { code: "YEONCHEON", name: "연천군" },
    ],
  },
  {
    code: "GANGWON",
    name: "강원특별자치도",
    cities: [
      { code: "CHUNCHEON", name: "춘천시" },
      { code: "WONJU", name: "원주시" },
      { code: "GANGNEUNG", name: "강릉시" },
      { code: "DONGHAE", name: "동해시" },
      { code: "TAEBAEK", name: "태백시" },
      { code: "SOKCHO", name: "속초시" },
      { code: "SAMCHEOK", name: "삼척시" },
      { code: "HONGCHEON", name: "홍천군" },
      { code: "HOENGSEONG", name: "횡성군" },
      { code: "YEONGWOL", name: "영월군" },
      { code: "PYEONGCHANG", name: "평창군" },
      { code: "JEONGSEON", name: "정선군" },
      { code: "CHEORWON", name: "철원군" },
      { code: "HWACHEON", name: "화천군" },
      { code: "YANGGU", name: "양구군" },
      { code: "INJE", name: "인제군" },
      { code: "GOSEONG_GW", name: "고성군" },
      { code: "YANGYANG", name: "양양군" },
    ],
  },
  {
    code: "CHUNGBUK",
    name: "충청북도",
    cities: [
      { code: "CHEONGJU", name: "청주시" },
      { code: "CHUNGJU", name: "충주시" },
      { code: "JECHEON", name: "제천시" },
      { code: "BOEUN", name: "보은군" },
      { code: "OKCHEON", name: "옥천군" },
      { code: "YEONGDONG", name: "영동군" },
      { code: "JEUNGPYEONG", name: "증평군" },
      { code: "JINCHEON", name: "진천군" },
      { code: "GOESAN", name: "괴산군" },
      { code: "EUMSEONG", name: "음성군" },
      { code: "DANYANG", name: "단양군" },
    ],
  },
  {
    code: "CHUNGNAM",
    name: "충청남도",
    cities: [
      { code: "CHEONAN", name: "천안시" },
      { code: "GONGJU", name: "공주시" },
      { code: "BORYEONG", name: "보령시" },
      { code: "ASAN", name: "아산시" },
      { code: "SEOSAN", name: "서산시" },
      { code: "NONSAN", name: "논산시" },
      { code: "GYERYONG", name: "계룡시" },
      { code: "DANGJIN", name: "당진시" },
      { code: "GEUMSAN", name: "금산군" },
      { code: "BUYEO", name: "부여군" },
      { code: "SEOCHEON", name: "서천군" },
      { code: "CHEONGYANG", name: "청양군" },
      { code: "HONGSEONG", name: "홍성군" },
      { code: "YESAN", name: "예산군" },
      { code: "TAEAN", name: "태안군" },
    ],
  },
  {
    code: "JEONBUK",
    name: "전북특별자치도",
    cities: [
      { code: "JEONJU", name: "전주시" },
      { code: "GUNSAN", name: "군산시" },
      { code: "IKSAN", name: "익산시" },
      { code: "JEONGEUP", name: "정읍시" },
      { code: "NAMWON", name: "남원시" },
      { code: "GIMJE", name: "김제시" },
      { code: "WANJU", name: "완주군" },
      { code: "JINAN", name: "진안군" },
      { code: "MUJU", name: "무주군" },
      { code: "JANGSU", name: "장수군" },
      { code: "IMSIL", name: "임실군" },
      { code: "SUNCHANG", name: "순창군" },
      { code: "GOCHANG", name: "고창군" },
      { code: "BUAN", name: "부안군" },
    ],
  },
  {
    code: "JEONNAM",
    name: "전라남도",
    cities: [
      { code: "MOKPO", name: "목포시" },
      { code: "YEOSU", name: "여수시" },
      { code: "SUNCHEON", name: "순천시" },
      { code: "NAJU", name: "나주시" },
      { code: "GWANGYANG", name: "광양시" },
      { code: "DAMYANG", name: "담양군" },
      { code: "GOKSEONG", name: "곡성군" },
      { code: "GURYE", name: "구례군" },
      { code: "GOHEUNG", name: "고흥군" },
      { code: "BOSEONG", name: "보성군" },
      { code: "HWASUN", name: "화순군" },
      { code: "JANGHEUNG", name: "장흥군" },
      { code: "GANGJIN", name: "강진군" },
      { code: "HAENAM", name: "해남군" },
      { code: "YEONGAM", name: "영암군" },
      { code: "MUAN", name: "무안군" },
      { code: "HAMPYEONG", name: "함평군" },
      { code: "YEONGGWANG", name: "영광군" },
      { code: "JANGSEONG", name: "장성군" },
      { code: "WANDO", name: "완도군" },
      { code: "JINDO", name: "진도군" },
      { code: "SINAN", name: "신안군" },
    ],
  },
  {
    code: "GYEONGBUK",
    name: "경상북도",
    cities: [
      { code: "POHANG", name: "포항시" },
      { code: "GYEONGJU", name: "경주시" },
      { code: "GIMCHEON", name: "김천시" },
      { code: "ANDONG", name: "안동시" },
      { code: "GUMI", name: "구미시" },
      { code: "YEONGJU", name: "영주시" },
      { code: "YEONGCHEON", name: "영천시" },
      { code: "SANGJU", name: "상주시" },
      { code: "MUNGYEONG", name: "문경시" },
      { code: "GYEONGSAN", name: "경산시" },
      { code: "GUNWI", name: "군위군" },
      { code: "UISEONG", name: "의성군" },
      { code: "CHEONGSONG", name: "청송군" },
      { code: "YEONGYANG", name: "영양군" },
      { code: "YEONGDEOK", name: "영덕군" },
      { code: "CHEONGDO", name: "청도군" },
      { code: "GORYEONG", name: "고령군" },
      { code: "SEONGJU", name: "성주군" },
      { code: "CHILGOK", name: "칠곡군" },
      { code: "YECHEON", name: "예천군" },
      { code: "BONGHWA", name: "봉화군" },
      { code: "ULJIN", name: "울진군" },
      { code: "ULLEUNG", name: "울릉군" },
    ],
  },
  {
    code: "GYEONGNAM",
    name: "경상남도",
    cities: [
      { code: "CHANGWON", name: "창원시" },
      { code: "JINJU", name: "진주시" },
      { code: "TONGYEONG", name: "통영시" },
      { code: "SACHEON", name: "사천시" },
      { code: "GIMHAE", name: "김해시" },
      { code: "MIRYANG", name: "밀양시" },
      { code: "GEOJE", name: "거제시" },
      { code: "YANGSAN", name: "양산시" },
      { code: "UIRYEONG", name: "의령군" },
      { code: "HAMAN", name: "함안군" },
      { code: "CHANGNYEONG", name: "창녕군" },
      { code: "GOSEONG_GN", name: "고성군" },
      { code: "NAMHAE", name: "남해군" },
      { code: "HADONG", name: "하동군" },
      { code: "SANCHEONG", name: "산청군" },
      { code: "HAMYANG", name: "함양군" },
      { code: "GEOCHANG", name: "거창군" },
      { code: "HAPCHEON", name: "합천군" },
    ],
  },
  {
    code: "JEJU",
    name: "제주특별자치도",
    cities: [
      { code: "JEJU_CITY", name: "제주시" },
      { code: "SEOGWIPO", name: "서귀포시" },
    ],
  },
];

export function buildRegionCode(siDoCode: string, cityCode?: string): string {
  return cityCode ? `${siDoCode}_${cityCode}` : siDoCode;
}

export function buildRegionName(siDoName: string, cityName?: string): string {
  return cityName ? `${siDoName} ${cityName}` : siDoName;
}
